### ISSUE TITLE
Create the Divider primitive component

### ISSUE THREAD

**Issue by wesleycole** [skyverge/kodiak-ui#105]
The `Divider` component will render an `hr` tag and should be able to be styled with `variants` or the `sx` prop. The default color of the divider line should be the `muted` property from the theme. 

`Divider` should accept an `orientation` prop with the following accepted values: `horizontal` and `vertical` with `horizontal` as the default.

The component will live in the `@kodiak-ui/primitives` package and should have its own entry point just like the other primitive components.

**Example usage**

```tsx
<Divider variants="md" />
<Divider sx={{ borderColor: 'primary' }} />
```

**Comment by Shaun2D2** [comment]
I can take this issue, please assign to me

**Comment by wesleycole** [comment]
Awesome, thanks @Shaun2D2. You've been assigned!
