### ISSUE TITLE
Create useNumberFormatter for formatting numbers based on locale and currency

### ISSUE THREAD

**Issue by wesleycole** [skyverge/kodiak-ui#108]
Creating `useNumberFormatter` will allow us to quickly format numbers based on a locale and whether it is a currency or not and display the appropriate number format to the user. 

Inspiration: https://react-spectrum.adobe.com/react-aria/useNumberFormatter.html

The hook should be a basic wrapper for [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat) and accept all of the same options.

**Comment by lukasslivko** [comment]
Can I take it?

**Comment by wesleycole** [comment]
Sure!

**Comment by lukasslivko** [comment]
@wesleycole Please assign me to this issue thx.

**Comment by lukasslivko** [comment]
I am busy right now. It will be done by the end of the week ok?

**Comment by wesleycole** [comment]
Yep, if you can't get to it by Friday remove yourself as an assignee so that someone else can pick it up.

**Comment by lukasslivko** [comment]
It will be done.
