### ISSUE TITLE
Move useLoadImage out of the Avatar component and into the hooks package

### ISSUE THREAD

**Issue by wesleycole** [skyverge/kodiak-ui#113]
The `useLoadImage` hook should be moved from the Avatar component and into the hooks package with its own entry point. Avatar should be updated to import `useLoadImage` from `@kodiak-ui/hooks`. 

We need to write tests and documentation for this hook as well.

**Comment by manas2297** [comment]
I would like to work on this issue.

**Comment by wesleycole** [comment]
@manas2297 thanks! I will assign the issue to you soon.

**Comment by manas2297** [comment]
@wesleycole  Can you please tell me how to add entry points for the hooks. I have added the ```useLoadImage``` hook in ```@kodak-ui/hooks/src``` folder.

**Comment by wesleycole** [comment]
@manas2297 sure! So we use `preconstruct` for compiling everyting. You can read more about exporting an entrypoint [here](https://preconstruct.tools/tutorials/multiple-entrypoints).

But take these steps and you should be done.

- Add 'use-load-image' to the `entryPoints` array in the package.json file for the hooks package.
- Run `yarn preconstruct fix` and follow the prompts in the terminal
- If need be, you will need to update the `preconstruct` object in the package.json file for the entrypoint to point to the correct src file.

```
// example preconstruct config for an entry point
"preconstruct": {
    "source": "../src/useControlled"
  }
```
