### ISSUE TITLE
Object styles should be hoisted by a babel plugin

### ISSUE THREAD

**Issue by alexanderchan** [skyverge/kodiak-ui#115]
Emotion hoists pure static styles up in their [babel plugin](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion#example) so that they don't trigger re-renders.  It would be ideal to have a plugin that could hoist any pure style out as well.

- multiple properties are configurable (css, sx, style)
- the wrapping function is configurable (ie, wrap with `css`)

It's possible that https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements could also assist with this but it appears to need a whitelist of components that an object is ok for.  It would be nice not to have to maintain a list and remember to have to add it to this list each time.  Check if there's any other pure prop hoisting plugin can do this as well before developing this.

**Comment by wesleycole** [comment]
@all-contributors add @alexanderchan for code and ideas
